-- MariaDB schema for gd-ads-site

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(32) PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  total_views INT UNSIGNED NOT NULL DEFAULT 0,
  total_clicks INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS advertisements (
  ad_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(32) NOT NULL,
  level_id VARCHAR(64) NOT NULL,
  type TINYINT UNSIGNED NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ad_id),
  KEY idx_user_id (user_id),
  CONSTRAINT fk_ads_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS views (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ad_id BIGINT UNSIGNED NOT NULL,
  user_id VARCHAR(32) NOT NULL,
  timestamp DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_ad_id (ad_id),
  KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clicks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ad_id BIGINT UNSIGNED NOT NULL,
  user_id VARCHAR(32) NOT NULL,
  timestamp DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_ad_id (ad_id),
  KEY idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
