-- MariaDB schema for gd-ads-site

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(32) PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(255) NOT NULL DEFAULT '',
    total_views BIGINT UNSIGNED NOT NULL DEFAULT 0,
    total_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    banned BOOLEAN NOT NULL DEFAULT FALSE,
    boost_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS advertisements (
    ad_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(32) NOT NULL,
    level_id INT(11) NOT NULL,
    type TINYINT UNSIGNED NOT NULL,
    views BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
    image_url VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pending BOOLEAN NOT NULL DEFAULT TRUE,
    boost_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (ad_id),
    KEY idx_user_id (user_id),
    CONSTRAINT fk_ads_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS views (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ad_id BIGINT UNSIGNED NOT NULL,
    user_id VARCHAR(32) NOT NULL,
    timestamp DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_ad_id (ad_id),
    KEY idx_user_id (user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS clicks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ad_id BIGINT UNSIGNED NOT NULL,
    user_id VARCHAR(32) NOT NULL,
    timestamp DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_ad_id (ad_id),
    KEY idx_user_id (user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(32) NOT NULL,
    session_id varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_user_id (user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS argon (
    account_id int(11) NOT NULL,
    authtoken varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    valid_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (account_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;