name: GD Ads Site
# mainly for testing purposes

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build site source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Node dependencies
        run: npm ci

      - name: Build project (tsc, vite, bridge)
        run: npm run build

      - name: Ensure bridge binary is executable
        run: |
          if [ -f build/bridge ]; then chmod +x build/bridge; fi

      - name: Upload frontend artifact
        run: |
          rm -rf artifacts/frontend-dist
          mkdir -p artifacts/frontend-dist/dist
          cp -r dist/* artifacts/frontend-dist/dist/

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: artifacts/frontend-dist

      - name: Upload bridge binary artifact
        run: |
          rm -rf artifacts/bridge-binary
          mkdir -p artifacts/bridge-binary
          cp build/bridge artifacts/bridge-binary/bridge

      - name: Upload bridge binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridge-binary
          path: artifacts/bridge-binary

  package:
    name: Package release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend-dist

      - name: Download bridge artifact
        uses: actions/download-artifact@v4
        with:
          name: bridge-binary
          path: bridge-binary

      - name: Create release bundle
        run: |
          set -euo pipefail
          rm -rf release
          mkdir -p release

          if [ -d frontend-dist/dist ]; then
            cp -r frontend-dist/dist release/dist
          else
            echo "frontend-dist/dist not found" >&2
            exit 1
          fi

          if [ -f bridge-binary/bridge ]; then
            cp bridge-binary/bridge release/
          else
            echo "bridge-binary/bridge not found" >&2
            exit 1
          fi

      - name: Create release tarball
        run: |
          tar -czf release.tar.gz -C release .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GDAdsSite
          path: release.tar.gz
