name: Build and Package

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build (Vite + Go) and package
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.25"

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Install Node dependencies
              run: npm ci

            - name: Build project (tsc, vite, bridge)
              run: npm run build

            - name: Ensure bridge binary is executable
              run: |
                  if [ -f build/bridge ]; then chmod +x build/bridge; fi

            - name: Package artifact
              run: |
                  mkdir -p release
                  if [ -d dist ]; then cp -r dist release/; fi
                  if [ -f build/bridge ]; then cp build/bridge release/; fi

            - name: Upload release artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release
                  path: release
